### PR TITLE
added Container.MustGet() function

### PR DESCRIPTION
**Pull request by vgarvardt**

### CODE REVIEW

**Comment by drgomesp** [comment]
Thanks for the pull request, @vgarvardt.

Although I appreciate your contribution, I'm having trouble finding a reason for a `MustGet` method.

We can achieve the same results with

``` go
service, err := container.Get("foo)

if err !=nil {
    panic(err)
}
```

I don't think the container should panic if a service is not found.

**Comment by vgarvardt** [comment]
It's just wrap for the code above to avoid code duplications - e.g. in my case missed id in container alway must panic, so MustGet saves 4 lines of code for each usage. Same as html/template.Must()  and many other examples.

**Comment by drgomesp** [comment]
I understand your point, but my question (which is more of a rhetoric question) is: does the container have the responsibility of panicking if a service is not found?

For example, when you hit a web page the doesn't exist, does the response comes as 500 or 404?

**Comment by tomsquest** [comment]
@drgomesp I do think the container must panic when an asked dependency is not found, **or** better the asker can choose, via `Get` and `MustGet`.
- Spring DI (java) panics when a dependency is not found (`context.getBean(Foo.class)`)
- Persistance API offer the choice: either you `get()` which returns possibly null, or you `load()` which throw an error

**Comment by vgarvardt** [comment]
> For example, when you hit a web page the doesn't exist, does the response comes as 500 or 404?

For example when you hit a config loader or any other important resource that does not exist.

**Review by drgomesp — CHANGES_REQUESTED** [review]
Fair enough. @vgarvardt just make sure to add the test case for that scenario and I'll merge it.

**Comment by vgarvardt** [comment]
Added couple tests.

**Review by drgomesp — APPROVED** [review]

**Comment by drgomesp** [comment]
Thank you, @vgarvardt!

**Pull request merged**
